name: Fetch and Update PDF

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual run

jobs:
  fetch_and_update_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Decode Google API credentials
      run: |
        echo "${{ secrets.GOOGLE_CREDENTIALS_B64 }}" | base64 -d > credentials.json
        echo "${{ secrets.GOOGLE_TOKEN_B64 }}" | base64 -d > token.json


    #- name: Set up GitHub authentication
     #run: |
          #git config user.name "github-actions"
          #git config user.email "github-actions@github.com"
          #git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Lesage974/QRNews.git
          #git remote -v


    - name: Run fetch_pdf.py
      run: python3 fetch_pdf.py

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add latest.pdf
        git commit -m "Update PDF via GitHub Actions" || echo "Nothing to commit"
    
        # Force remote to use the token
        git remote remove origin
        git remote add origin https://x-access-token:$GH_PAT@github.com/Lesage974/QRNews.git
        git remote -v
        git push origin main
