name: Fetch and Update PDF

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual run

jobs:
  fetch_and_update_pdf:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Write Google API credentials
      run: |
        if [ -z "${{ secrets.GOOGLE_CREDENTIALS }}" ]; then echo "Missing GOOGLE_CREDENTIALS"; exit 1; fi
        if [ -z "${{ secrets.GOOGLE_TOKEN }}" ]; then echo "Missing GOOGLE_TOKEN"; exit 1; fi
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json
        echo "${{ secrets.GOOGLE_TOKEN }}" > token.json
        cat credentials.json  # TEMP: debug only, remove after testing
        cat token.json        # TEMP: debug only, remove after testing


    - name: Set up GitHub authentication
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Lesage974/QRNews.git

    - name: Run fetch_pdf.py
      run: python3 fetch_pdf.py

    - name: Commit and push changes
      run: |
        git add latest.pdf
        git commit -m "Update PDF via GitHub Actions"
        git push origin main
